# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 873)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 50, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 50, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Spin_input_table = QtWidgets.QSpinBox(self.centralwidget)
        self.Spin_input_table.setMinimum(15)
        self.Spin_input_table.setMaximum(50)
        self.Spin_input_table.setObjectName("Spin_input_table")
        self.horizontalLayout.addWidget(self.Spin_input_table)
        self.Obr_button = QtWidgets.QPushButton(self.centralwidget)
        self.Obr_button.setObjectName("Obr_button")
        self.horizontalLayout.addWidget(self.Obr_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Table_input = QtWidgets.QTableWidget(self.centralwidget)
        self.Table_input.setEnabled(True)
        self.Table_input.setObjectName("Table_input")
        self.Table_input.setColumnCount(0)
        self.Table_input.setRowCount(0)
        self.verticalLayout.addWidget(self.Table_input)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.Table_result = QtWidgets.QTableWidget(self.centralwidget)
        self.Table_result.setMaximumSize(QtCore.QSize(400, 16777215))
        self.Table_result.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Table_result.setObjectName("Table_result")
        self.Table_result.setColumnCount(0)
        self.Table_result.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.Table_result)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.GraphWidget = PlotWidget(self.centralwidget)
        self.GraphWidget.setMinimumSize(QtCore.QSize(400, 400))
        self.GraphWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.GraphWidget.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.GraphWidget.setObjectName("GraphWidget")
        self.horizontalLayout_3.addWidget(self.GraphWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Obr_button.setText(_translate("MainWindow", "Обработка"))
        self.menu.setTitle(_translate("MainWindow", "Опции"))
        self.action.setText(_translate("MainWindow", "Настройки"))
from pyqtgraph import PlotWidget
